version: "3.9"

services:
  backend:
    container_name: rest_api
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=True
      # other environment vars like hosts and Django secret key
