version: "3.9"

services:
  backend:
    container_name: rest_api
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=True
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


  frontend:
    container_name: frontend
    build:
      context: ./frontend
    command: npm run dev
    ports:
       - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

volumes:
  pgdata:
